language: go

go:
  - 1.3.3
  - 1.4.2
  - 1.5.1
before_install:
  # `go test` does not support coverage for multiple packages
  # - go get github.com/axw/gocov/gocov
  # - go get github.com/mattn/goveralls
  # - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify/suite
  - go get github.com/tools/godep
  - godep restore
script:
    - make test
